services:
  - type: web
    name: daily-insights
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m gunicorn run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.12
